# Data Science Tools and Ecosystem

In this notebook, Data Science Tools and Ecosystem are summarized.

Some of the popular languages that Data Scientists use are:


1.   Python
2.   R
3.   SQL

**Objetives:**

*   Python
*   R
* SQL
* Pandas
* Plotly

Some of the commonly used libraries used by Data Scientists include:


1.   pandas
2.   plotly
3.   scipy

| Data Science Tools |
| ------------------ |
| Jupyter Notebook |
| RStudio |
| ApacheSpark |

### Below are a few examples of evaluating arithmetic expressions in Python

In [2]:
#This a simple arithmetic expression to mutiply then add integers
(3*4)+5

17

In [3]:
#This will convert 200 minutes to hours by diving by 60
200/60

3.3333333333333335

## Author
Natalia